### ISSUE TITLE
Fatal bug in files-find-used content

### ISSUE THREAD

**Issue by danverde** [byuitechops/files-find-used-content#4]
```
var match = source.match(reWrapDetails);
                     ^

RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (native)
    at getWrapDetails (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\lodash\_getWrapDetails.js:13:22)
    at setWrapToString (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\lodash\_setWrapToString.js:18:75)
    at createWrap (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\lodash\_createWrap.js:103:10)
    at Object.<anonymous> (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\lodash\bind.js:51:10)
    at apply (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\lodash\_apply.js:16:25)
    at Object.bind (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\lodash\_overRest.js:32:12)
    at initialize.module.exports (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\cheerio\lib\cheerio.js:54:27)
    at new initialize (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\cheerio\lib\static.js:34:20)
```

**Comment by maeashley** [comment]
This might be a recurring issue with this code, since it is recursive. I'm not sure how to handle this.

**Comment by danverde** [comment]
Essentially too many recursive calls have been made. It might be a recursive link caused by the structure of the course files, or it could also be that the course was simply too large and it was too taxing to search through everything. Putting a setTimeout with a wait time of may fix this issue if it was caused by the size of the course

**Comment by danverde** [comment]
Switching to promises would remove the problem either way

**Comment by zachintosh** [comment]
Resolved....I think.
