### ISSUE TITLE
fatal error | item.getHtml is not a function

### ISSUE THREAD

**Issue by danverde** [byuitechops/files-find-used-content#9]
Brightspace OU 65679
```
(node:13672) UnhandledPromiseRejectionWarning: TypeError: item.getHtml is not a function
    at identifyFileLinks (c:\Users\danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\files-find-used-content\main.js:10:102)
    at Array.reduce (<anonymous>)
    at c:\Users\danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\files-find-used-content\main.js:60:34
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by danverde** [comment]
Also occurred on course with ID: 394706

**Comment by danverde** [comment]
I believe this was an issue with NPM running an older version
